name: export-silero-vad-v62-to-rknn

on:
  workflow_dispatch:

concurrency:
  group: export-silero-vad-v62-to-rknn-${{ github.ref }}
  cancel-in-progress: true

jobs:
  export-silero-vad-v62-to-rknn:
    name: export silero-vad to rknn
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade \
            pip \
            "numpy<2" \
            torch==2.0.0+cpu -f https://download.pytorch.org/whl/torch \
            onnx \
            onnxruntime==1.17.1 \
            librosa \
            soundfile \
            onnxsim

          curl -SL -O https://huggingface.co/csukuangfj/rknn-toolkit2/resolve/main/rknn_toolkit2-2.1.0%2B708089d1-cp310-cp310-linux_x86_64.whl
          pip install ./*.whl "numpy<=1.26.4"

      - name: Run
        shell: bash
        run: |
          cd scripts/silero_vad/v6
          chmod +x *
          curl -SL -O https://github.com/snakers4/silero-vad/raw/refs/heads/master/src/silero_vad/data/silero_vad.onnx
          ls -lh silero_vad.onnx
          for platform in rk3588 rk3576 rk3568 rk3566 rk3562; do
          echo "Platform: $platform"
            ./export-rknn.py --in-model ./silero_vad.onnx --out-model silero-vad-v6-$platform.rknn  --target-platform $platform
            ls -lh silero-vad-v6-$platform.rknn
          done

      - name: Collect files
        shell: bash
        run: |
          cd scripts/silero_vad/v6
          ls -lh
          mv *.rknn ../../..

     
      
